name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set tag
      id: tag
      run: echo "::set-output name=tag::$(date +%s)"
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: docker build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USER}}/pdfact-service:latest , ${{secrets.DOCKER_USER}}/pdfact-service:${{ steps.tag.outputs.tag }}
    - name: docker push readme
      uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASSWORD}}
      with:
        destination_container_repo: dnlbauer/pdfact-service
        provider: dockerhub
        short_description: 'Analyze pdf files with pdfact using a simple web API.'
        readme_file: 'README.md'

