name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set tag
      id: tag
      run: echo "::set-output name=tag::$(date +%s)"
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: docker build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USER}}/pdfact-service:latest , ${{secrets.DOCKER_USER}}/pdfact-service:${{ steps.tag.outputs.tag }}
